FROM alpine:latest

LABEL maintainer="Bineyond <bineyond@gmail.com>" \
    org.opencontainers.image.title="SFTP Server (Alpine)" \
    org.opencontainers.image.source="https://github.com/bineyond/sftp"

# Steps done in one RUN layer:
# - Install upgrades and new packages
# - OpenSSH needs /var/run/sshd to run
# - Remove generic host keys, entrypoint generates unique keys
RUN apk update && apk upgrade && \
    apk add --no-cache bash shadow openssh-server-pam openssh-sftp-server acl && \
    rm -rf /var/cache/apk/* && \
    ln -s /usr/sbin/sshd.pam /usr/sbin/sshd && \
    mkdir -p /var/run/sshd && \
    rm -f /etc/ssh/ssh_host_*key*

COPY files/sshd_config /etc/ssh/sshd_config
COPY files/entrypoint /

EXPOSE 22

ENTRYPOINT ["/entrypoint"]
